name = "creator-tools-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"

# ============================================
# D1 Database Configuration (COMMENTED OUT)
# ============================================
# Uncomment and configure after initial deployment
# 
# To enable:
# 1. Create database: wrangler d1 create creator_tools_db
# 2. Update database_id below with actual ID from step 1
# 3. Initialize schema: wrangler d1 execute creator_tools_db --file=./schema.sql
# 4. Uncomment the section below
# 5. Redeploy
#
# [[d1_databases]]
# binding = "DB"
# database_name = "creator_tools_db"
# database_id = "YOUR_ACTUAL_DATABASE_ID_HERE"

# Environment variables
[vars]
ENVIRONMENT = "production"

# ============================================
# Secrets (set with: wrangler secret put <KEY>)
# ============================================
# Required for platform integrations:
# - TWITTER_API_KEY
# - TWITTER_API_SECRET
# - LINKEDIN_CLIENT_ID
# - LINKEDIN_CLIENT_SECRET
# - INSTAGRAM_APP_ID
# - INSTAGRAM_APP_SECRET

# ============================================
# Cron Triggers (COMMENTED OUT - Requires DB)
# ============================================
# Uncomment after database is configured
# [triggers]
# crons = ["*/5 * * * *"]
