name = "creator-tools-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"

# D1 Database (Optional - configure after first deployment)
# To set up:
# 1. Run: wrangler d1 create creator_tools_db
# 2. Copy the database_id from output and paste below
# 3. Run: wrangler d1 execute creator_tools_db --file=./schema.sql
[[d1_databases]]
binding = "DB"
database_name = "creator_tools_db"
database_id = "PLACEHOLDER_CONFIGURE_AFTER_DEPLOYMENT" # Replace with actual database ID

# Environment variables (use wrangler secret put for sensitive values)
[vars]
ENVIRONMENT = "production"

# Secrets (set with: wrangler secret put <KEY>)
# TWITTER_API_KEY
# TWITTER_API_SECRET
# LINKEDIN_CLIENT_ID
# LINKEDIN_CLIENT_SECRET
# INSTAGRAM_APP_ID
# INSTAGRAM_APP_SECRET

# Cron trigger for publishing scheduled posts
[triggers]
crons = ["*/5 * * * *"] # Every 5 minutes

# Custom routes (Optional - configure custom domain after deployment)
# Uncomment and configure these after setting up your custom domain in Cloudflare
# [route]
# pattern = "api.creator-tools.com/*"
# zone_name = "creator-tools.com"
