name = "creator-tools-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"

# ============================================
# D1 Database Configuration (COMMENTED OUT)
# ============================================
# The database configuration is commented out to allow initial deployment.
# Wrangler will reject invalid/placeholder database IDs.
#
# To enable database functionality after deployment:
# 1. Create database: wrangler d1 create creator_tools_db
# 2. Copy the database_id from the output
# 3. Uncomment the [[d1_databases]] section below
# 4. Replace YOUR_DATABASE_ID_HERE with the actual database ID
# 5. Initialize schema: wrangler d1 execute creator_tools_db --file=./schema.sql --remote
# 6. Redeploy: wrangler deploy
# 
# [[d1_databases]]
# binding = "DB"
# database_name = "creator_tools_db"
# database_id = "YOUR_DATABASE_ID_HERE"

# Environment variables (use wrangler secret put for sensitive values)
[vars]
ENVIRONMENT = "production"

# Secrets (set with: wrangler secret put <KEY>)
# TWITTER_API_KEY
# TWITTER_API_SECRET
# LINKEDIN_CLIENT_ID
# LINKEDIN_CLIENT_SECRET
# INSTAGRAM_APP_ID
# INSTAGRAM_APP_SECRET

# ============================================
# Cron Triggers (COMMENTED OUT - Requires DB)
# ============================================
# Uncomment after database is configured
# [triggers]
# crons = ["*/5 * * * *"]
