name: Check Deployment Secrets

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    name: Verify Cloudflare Secrets Configuration
    steps:
      - name: Check if secrets are configured
        run: |
          echo "🔍 Checking Cloudflare deployment secrets..."
          
          SECRETS_MISSING=0
          
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "❌ CLOUDFLARE_API_TOKEN is not configured"
            SECRETS_MISSING=1
          else
            echo "✅ CLOUDFLARE_API_TOKEN is configured"
          fi
          
          if [ -z "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" ]; then
            echo "❌ CLOUDFLARE_ACCOUNT_ID is not configured"
            SECRETS_MISSING=1
          else
            echo "✅ CLOUDFLARE_ACCOUNT_ID is configured"
          fi
          
          echo ""
          
          if [ $SECRETS_MISSING -eq 1 ]; then
            echo "⚠️  DEPLOYMENT WILL FAIL - Missing required secrets"
            echo ""
            echo "📚 Quick Fix Guide:"
            echo "1. Get API token: https://dash.cloudflare.com/profile/api-tokens"
            echo "2. Get account ID: https://dash.cloudflare.com (right sidebar)"
            echo "3. Add to GitHub: https://github.com/${{ github.repository }}/settings/secrets/actions"
            echo "   - Add secret: CLOUDFLARE_API_TOKEN"
            echo "   - Add secret: CLOUDFLARE_ACCOUNT_ID"
            echo ""
            echo "📖 Full guide: See DEPLOYMENT_RUN_18797232869_RESOLUTION.md"
            echo ""
            exit 1
          else
            echo "✅ All required secrets are configured!"
            echo "🚀 Deployment should succeed"
          fi
